Bug/disk space issue
yugabyte/yugabyte-db-thirdparty pull request #166
Opened 2023-03-03 17:01 UTC by saratkumar-yb

2023-03-07 16:39 UTC, svarnau approved these changes

2023-03-07 23:46 UTC, mbautin requested changes
Please properly rebase this on the upstream code. This PR is making changes to abseil and tcmalloc, and I highly suspect that was not intended.

2023-03-08 22:03 UTC, SrivastavaAnubhav commented
@mbautin @saratkumar-yb was testing whether his changes would make my build pass (it was failing because of disk space issues). It seems like it does. But @saratkumar-yb, maybe it's better to just commit your code and then I'll rerun on my branch.

2023-03-08 23:34 UTC, mbautin commented
Pushed this change as https://github.com/yugabyte/yugabyte-db-thirdparty/commit/bcb96d63d950be3915295f8d55d5a57243e3189b

Thanks @saratkumar-yb @svarnau @SrivastavaAnubhav !

2023-03-08 23:34 UTC, closed without merging